require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported  # iOS 12+
prepare_react_native_project!

target 'FaceAuthOffline' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # TFLite with CoreML / GPU delegate
  pod 'TensorFlowLiteSwift', '~> 2.14.0'
  pod 'TensorFlowLiteSwift/CoreML', '~> 2.14.0'

  # Vision Camera
  pod 'VisionCamera', :path => '../node_modules/react-native-vision-camera'

  # Fast TFLite
  pod 'RNFastTflite', :path => '../node_modules/react-native-fast-tflite'

  target 'FaceAuthOfflineTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath], :mac_catalyst_enabled => false)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
